name: Build macOS Dev

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'

env:
  FLUTTER_VERSION: '3.38.5'

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.21.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Install deps
        run: brew install tree

      - name: Download core libs
        run: make macos-libs

      - name: Prepare (pub get + codegen + translations)
        run: make common-prepare

      - name: Build macOS
        run: flutter build macos --release --dart-define sentry_dsn=

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: Hiddify-Dev-macOS
          path: build/macos/Build/Products/Release/
          retention-days: 7
